[project]
name = "angr-ctf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "angr>=9.2.185",
    "ipython>=8.37.0",
    "jinja2>=3.1.6",
    "pwntools>=4.14.1",
    "templite>=0.2.1",
]
